### ISSUE TITLE
Character encoding can cause issues in Meneco 2.0.0 installation, fixed by modifying setup.py

### ISSUE THREAD

**Issue by AdityaVaze** [bioasp/meneco#22]
Installation of Meneco 2.0.0 was causing the following error on my system: 

`UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2511: character maps to <undefined>`

Fixed by specifying the encoding in setup.py:
Change `long_description=open('README.md').read(),` to `long_description=open('README.md', encoding="utf8").read(),`

Adding an issue for any other users who may have encountered this problem during installation.

**Comment by cfrioux** [comment]
Hi @AdityaVaze , could you tell us more about your system so that we can reproduce and fix the error? (OS, python version, conda....). Cheers

**Comment by AdityaVaze** [comment]
Yes, of course.
Windows 10 Home, Anaconda environment: conda version : 4.10.3, conda-build version : 3.21.5, python version : 3.7.10.final.0

**Comment by sthiele** [comment]
This has been fixed in 76908f6ced421ff338e530f288938a4aca1e202d.
