### ISSUE TITLE
query.get_unreproducible error 

### ISSUE THREAD

**Issue by shraddhakhirwadkar** [bioasp/meneco#24]
Hello, 
I was following the tutorial (https://hub.gke2.mybinder.org/user/bioasp-meneco-fwnncdlm/notebooks/meneco.ipynb), and I get stuck at the function query.get_unreproducible error(). I have attached a screenshot of the error. Does anyone know what can be done to fix this? Any help is appreciated. Thank you!
![image](https://user-images.githubusercontent.com/73715781/159368566-f0460ba7-941e-4e93-8a4d-e0a712858840.png)

**Comment by sthiele** [comment]
@shraddhakhirwadkar Thanks for reporting this. Looks like there is a regression in one of our dependencies. I have a look at.

**Comment by cfrioux** [comment]
This is probably due to the latest clyngor update that broke quite a few tools lately. 
See https://github.com/AuReMe/metage2metabo/issues/35
The fix is quite simple: https://github.com/cfrioux/miscoto/pull/14, adding `use_clingo_module=False` when calling `clyngor.solve`.

**Comment by shraddhakhirwadkar** [comment]
@cfrioux I tried adding use_clingo_module=False as an option in every clyngor.solve() in query.py but I am still running into the same error. Am I using the argument correctly? Thank you for your help.

**Comment by sthiele** [comment]
@shraddhakhirwadkar
I think I fixed the issue in the next branch, maybe you can test it.
The latest clyngor also breaks the python 3.6 support this maybe another issue.
Also the binder link you posted is outdated maybe you have something more permanent?

**Comment by sthiele** [comment]
@cfrioux I would prepare a new release if you agree.

**Comment by cfrioux** [comment]
Yes, works for me. Cheers!

**Comment by shraddhakhirwadkar** [comment]
Hi Sven, when would I expect a next release by? Also, I just wanted to check in to see if I can gap-fill AGORA SBML models using Meneco. Thank you,Shraddha From: Sven ThieleSent: March 23, 2022 3:30 AMTo: bioasp/menecoCc: shraddhakhirwadkar; MentionSubject: Re: [bioasp/meneco] query.get_unreproducible error (Issue ***@***.*** I would prepare a new release if you agree.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by shraddhakhirwadkar** [comment]
Hi Sven, when would I expect the next release by? Also, I just wanted to check in to see if I can gap-fill AGORA SBML models using Meneco. Thank you, Shraddha

**Comment by sthiele** [comment]
:wave: Hey  Shraddha
I just published a new release. It should be up now ... let me know if it works for you.
